export const C = {
  bg:           "#f2f4f6",
  bgCard:       "#ffffff",
  bgMuted:      "#f2f4f6",
  bgOverlay:    "rgba(0,0,0,0.4)",
  text:         "#1e2328",
  textSub:      "#4b5563",
  textMuted:    "#9ea5b0",
  border:       "#e8eaed",
  borderStrong: "#d1d5db",
  primary:      "#1daaed",
  primaryHover: "#17a2e0",
  primaryFg:    "#ffffff",
  primaryBg:    "#ddf2fc",
  primaryMuted: "#b3e5f9",
  success:      "#2db56a",
  successFg:    "#ffffff",
  successBg:    "#dff4e9",
  warning:      "#f59e0b",
  warningBg:    "#fffbeb",
  danger:       "#ff4d4d",
  dangerFg:     "#ffffff",
  dangerBg:     "#fff0f0",
  purple:       "#9b59d4",
  purpleBg:     "#f0e6f9",
  teal:         "#0D9488",
  tealBg:       "#F0FDFA",
} as const;

export const STATUS_CONFIG = {
  active:    { label: "진행중", color: "#1daaed", bg: "#ddf2fc" },
  upcoming:  { label: "예정",   color: "#9b59d4", bg: "#f0e6f9" },
  completed: { label: "완료",   color: "#2db56a", bg: "#dff4e9" },
} as const;
